CREATE TABLE customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_code VARCHAR(40) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_code UNIQUE (customer_code)
);

